<?php

/**
 * Implements hook_theme().
 */
function node_tree_theme($existing, $type, $theme, $path)
{
  /*
  return [
    'node_tree_nodetreeblock' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'node-tree-hierarchy-tree-block',
    ],
  ];
  */

  return [
    'bol-hierarchy-tree-block' => [],
  ];
}


function node_tree_preprocess_block(&$variables)
{
  if ($variables['configuration']['label'] == "NodeTreeBlock") {
    $variables['attributes']['id'] = ['node_tree'];
  }
}


//  https://drupal.stackexchange.com/a/200609/1082

/*

function MY_MODULE_theme($existing, $type, $theme, $path) {
  return [
    'node__video_teaser' => [
      'template' => 'node--video-teaser',
      'base hook' => 'node',
    ],
  ];
}


*/