<?php

/**
 * Implements hook_theme().
 */
function node_tree_theme($existing, $type, $theme, $path) {
    return [
      'node-tree-hierarchy-tree-block' => [
      ],
      'node-tree-content-display-block' => [
      ],
    ];
  }



//  https://drupal.stackexchange.com/a/200609/1082

/*

function MY_MODULE_theme($existing, $type, $theme, $path) {
  return [
    'node__video_teaser' => [
      'template' => 'node--video-teaser',
      'base hook' => 'node',
    ],
  ];
}


*/